In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('ripa_stops_datasd.csv')
data.head()

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,beat_name,pid,isstudent,perceived_limited_english,perceived_age,perceived_gender,gender_nonconforming,gend,gend_nc,perceived_lgbt
0,2443,CA0371100,SD,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",...,Pacific Beach 122,1,0,0,25,Male,0,1,NaN,No
1,2444,CA0371100,SD,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",...,Mission Beach 121,1,0,0,25,Male,0,1,NaN,No
2,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,1,0,0,30,Male,0,1,NaN,No
3,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,2,0,0,30,Female,0,2,NaN,No
4,2448,CA0371100,SD,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",...,Ocean Beach 614,1,0,0,23,Male,0,1,NaN,No

In [46]:
data.time_stop = data.time_stop.apply(lambda x: x[-8:] if len(x)>8 else x)

In [8]:
data = data.astype(str)

In [9]:
data.dtypes

stop_id                      object
ori                          object
agency                       object
exp_years                    object
date_stop                    object
time_stop                    object
stopduration                 object
stop_in_response_to_cfs      object
officer_assignment_key       object
assignment                   object
intersection                 object
address_block                object
land_mark                    object
address_street               object
highway_exit                 object
isschool                     object
school_name                  object
address_city                 object
beat                         object
beat_name                    object
pid                          object
isstudent                    object
perceived_limited_english    object
perceived_age                object
perceived_gender             object
gender_nonconforming         object
gend                         object
gend_nc                      object
perceived_lgbt               object
dtype: object

In [10]:
data.to_csv('fixed_ripa_stops_datasd.csv')